INSERT INTO USERS(USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ENABLE) VALUES ('obarra', '900', 'obarra@test.com', 'omar', 'barra', true);

INSERT INTO USERS(USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ENABLE) VALUES ('umar', '900', 'umar@test.com', 'omar', 'barra', true);

INSERT INTO USERS(USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ENABLE) VALUES ('delen', '900', 'delen@test.com', 'omar', 'barra', true);

INSERT INTO ROLES(NAME) VALUES('ROLE_USER');
INSERT INTO ROLES(NAME) VALUES('ROLE_ADMIN');

INSERT INTO USERS_ROLES(USERS_ID, ROLES_ID) VALUES(1,1);
INSERT INTO USERS_ROLES(USERS_ID, ROLES_ID) VALUES(1,2);
INSERT INTO USERS_ROLES(USERS_ID, ROLES_ID) VALUES(2,1);


