INSERT INTO PRODUCTS(NAME, PRICE, CREATE_AT)  VALUES ('Apple', 900, NOW());
INSERT INTO PRODUCTS(NAME, PRICE, CREATE_AT)  VALUES ('S8', 700, NOW());
INSERT INTO PRODUCTS(NAME, PRICE, CREATE_AT)  VALUES ('Ford', 1000, NOW());
INSERT INTO PRODUCTS(NAME, PRICE, CREATE_AT)  VALUES ('Mercedez', 2000, NOW());
INSERT INTO PRODUCTS(NAME, PRICE, CREATE_AT)  VALUES ('VW', 900, NOW());