INSERT INTO WEATHER_TYPE(WEATHER_TYPE_ID, NAME) VALUES (1, 'Rain');
INSERT INTO WEATHER_TYPE(WEATHER_TYPE_ID, NAME) VALUES (2, 'Drought');
INSERT INTO WEATHER_TYPE(WEATHER_TYPE_ID, NAME) VALUES (3, 'Optimum');